In [3]:
from bs4 import BeautifulSoup
# 파일 읽기
with open('greenData/member_data.xml','r',encoding='utf-8-sig') as f:
    # 파싱 => xml을 파싱해서 계층형 구조로 만들어줌
    soup = BeautifulSoup(f,'xml')

# 데이터 추출 (select => 내가 지정한 'member'안의 모든 것을 출력) => 단, 태그여야함
members = soup.select('member')

for m in members:
    name = m.select_one('name').text
    age = m.select_one('age').text
    city = m.select_one('city').text
    print(f"이름 : {name}, 나이 : {age}, 도시 : {city}")

이름 : 김철수, 나이 : 25, 도시 : 서울
이름 : 이영희, 나이 : 30, 도시 : 부산
이름 : 박민수, 나이 : 22, 도시 : 대전

json.loads() => JSON형식의 문자열을 파이썬 사전(Dict)로 변환
json.dumps() => 파이썬 사전(Dict) 데이터를 JSON 문자열로 변환

원래 아나콘다가 json을 받아오는데 혹여 에러가 난다면 import를 해야한다.

In [7]:
json_str = '{"name" : "Alice", "role" : "admin", "level" : 5}'

# JSON문자열을 사전으로 변환 => Decoding
data = json.loads(json_str)
print(data["name"], type(data))

# 사전을 JSON 문자열로 변환 => Incoding
user = {"id" : 7, "status" : "online"}
userJson = json.dumps(user, indent=4) # indent => 들여쓰기
print(userJson)

Alice <class 'dict'>
{
    "id": 7,
    "status": "online"
}

# pandas => 테이블형 데이터를 다룰 수 있는 다양한 기능을 가진 라이브러리이다.
# raw data => 아직 데이터 분석을 위해 정제되지 않은 기본 데이터
# pandas는 반드시 import 해서 사용한다.
# 데이터를 다루는 방식 2가지
    # 1. 시리즈(series)는 1차원 (행 하나 또는 열 하나)
    # 2. 데이터 프레임(DataFrame)은 2차원(테이블형) 데이터이다.

In [17]:
import pandas as pd # 실무에서는 대부분 pd로 축약함
# pd.판다스 함수() 의 형태로 호출해서 사용
# index는 행의 레이블을 의미한다. => 레이블 = 제목
# index를 지정하지 않으면 0부터 자동 지정한다.
# 지정된 경우 지정된 인덱스로 출력된다.
#seriesdata = pd.Series([70,80,90]) # => 인덱스를 지정하지 않음
seriesdata = pd.Series([70,80,90], index = ['국어','영어','수학']) # => 인덱스를 지정함
seriesdata
seriesdata.index = ['미술','과학','사회'] # => 인덱스를 변경함
seriesdata
# series 삭제 => del seriesdata['index이름']
del seriesdata['미술']
seriesdata

과학    80
사회    90
dtype: int64

# pandas 데이터 타입
# object => str 또는 혼용데이터 타입(문자열)
# int64 => 파이썬의 int(정수)
# float64 => 파이썬의 float(부동소숫점)
# bool => 파이썬의 bool 또는 boolean(True 또는 False)
# datetime64 => 날짜/시간
# timedelta => 두개의 datetime64간의 차이

In [24]:
seriesdata = pd.Series(['dave','alex','amir'])
seriesdata
seriesdata = pd.Series([1,2,3])
seriesdata # dtype: int64

# int64의 정수를 float64로 변경
# 부동 소수점 변경하는 명령어 => Series.astype(변경할 타입)
seriesdata.astype('float') # dtype: float64

seriesdata = pd.Series(['dave',1,2,3])
seriesdata # dtype: object

seriesdata = pd.Series([True,False,True])
seriesdata # dtype: bool

0    dave
1       1
2       2
3       3
dtype: object

# 데이터 프레임(DataFrame) => 2차원 테이블 형태의 데이터, 데이터 분석, 머신러닝에서 데이터 처리를 위해 주로 사용함
# 행(row) 와 열(column)으로 구성되어있다.
# 행의 레이블은 인덱스로, 열의 레이블은 컬럼으로 부른다.

In [79]:
df = pd.DataFrame({
    # "년도" : [2000,2012,2013],
    "미국" : [2.1,2.2,2.3],
    "한국" : [0.4,0.5,0.45],
    "중국" : [10,13,15]},
    index = [2000,2012,2013]
    )
# df = df.set_index('년도')
# df.index.name = '연도'
# df = df.reset_index('연도')
df
# df.values
# df.index # => Index([2000, 2012, 2013], dtype='int64')
# df.columns # => Index(['미국', '한국', '중국'], dtype='object')
# df.columns = {'일본', '독일', '프랑스'}
# df.set_index(값)

       미국    한국  중국
2000  2.1  0.40  10
2012  2.2  0.50  13
2013  2.3  0.45  15

# 데이터 프레임 데이터 접근하기
df.loc : index를 통해서 값을 찾음
df.iloc : index 번호를 통해서 값을 찾음 (0부터 시작)

In [101]:
df = pd.DataFrame({
    # "년도" : [2000,2012,2013],
    "미국" : [2.1,2.2,2.3],
    "한국" : [0.4,0.5,0.45],
    "중국" : [10,13,15]},
    index = [2000,2012,2013]
    )

df.loc[2000] # => index라는 데이터프레임의 레이블을 이용해 값을 출력
df.iloc[1] # => 이미 가지고있는 0부터 시작하는 index로 값을 출력

df['한국'][2000]

# 데이터 프레임에 컬럼(=열 => 세로줄) 삭제 => del
# del df['미국']


# 데이터 프레임에 행(=행 => 가로줄) 삭제 => drop([인덱스 이름])
df.drop([2000])
df

       미국    한국  중국
2000  2.1  0.40  10
2012  2.2  0.50  13
2013  2.3  0.45  15

In [103]:
import pandas as pd
data = {
    '대여소' : ['강남','강남','홍대','홍대','잠실','잠실'],
    '이용자수' : [120,150,80,90,200,180],
    '대여시간' : [30,45,20,25,60,55],
    '이용일자' : ['2024-01-01','2024-01-02','2024-01-01','2024-01-02','2024-01-01','2024-01-02']
}
df = pd.DataFrame(data)
df

  대여소  이용자수  대여시간        이용일자
0  강남   120    30  2024-01-01
1  강남   150    45  2024-01-02
2  홍대    80    20  2024-01-01
3  홍대    90    25  2024-01-02
4  잠실   200    60  2024-01-01
5  잠실   180    55  2024-01-02

In [105]:
# • Data자료를이용해이용자수가100명이상인데이터만출력하시오
# • 조건필터이용
# df[df['age'] > 20]
df[df['이용자수'] >= 100]

  대여소  이용자수  대여시간        이용일자
0  강남   120    30  2024-01-01
1  강남   150    45  2024-01-02
4  잠실   200    60  2024-01-01
5  잠실   180    55  2024-01-02

In [109]:
# • Data자료를이용해대여시간기준으로오름차순정렬하여출력하시오.
# • 조건필터이용
# df.sort_values(by='price') => default 오름차순
df.sort_values(by='대여시간')
df.sort_values(by='대여시간', ascending=False)
# 내림차순 => df.sort_values(by='price', ascending=False)

  대여소  이용자수  대여시간        이용일자
4  잠실   200    60  2024-01-01
5  잠실   180    55  2024-01-02
1  강남   150    45  2024-01-02
0  강남   120    30  2024-01-01
3  홍대    90    25  2024-01-02
2  홍대    80    20  2024-01-01

In [116]:
# • Data자료를이용해"총이용량" 컬럼을이용자수* 대여시간으로계산하여추가하시오.
df['총이용량'] = df['이용자수'] * df['대여시간']
df

  대여소  이용자수  대여시간        이용일자   총이용량
0  강남   120    30  2024-01-01   3600
1  강남   150    45  2024-01-02   6750
2  홍대    80    20  2024-01-01   1600
3  홍대    90    25  2024-01-02   2250
4  잠실   200    60  2024-01-01  12000
5  잠실   180    55  2024-01-02   9900

In [122]:
# • Data자료를이용해컬대여소별총이용자수구하여출력하시오.
# • 사용함수: groupby()
# df.groupby('대여소')['이용자수'].sum()
# 내림차순
df.groupby('대여소')['이용자수'].sum().sort_values(ascending = False)

대여소
잠실    380
강남    270
홍대    170
Name: 이용자수, dtype: int64

In [124]:
#• Data자료를이용해이용자수가100 이상인데이터만추출하여대여소별평균대여시간구하여 출력하시오.
result = df[df['이용자수'] >= 100]
result.groupby('대여소')['대여시간'].mean()

대여소
강남    37.5
잠실    57.5
Name: 대여시간, dtype: float64

In [125]:
# • Data자료를이용해대여소별"총이용량" 합계구하기
df['총이용량'] = df['이용자수'] * df['대여시간']
df.groupby('대여소')['총이용량'].sum()

대여소
강남    10350
잠실    21900
홍대     3850
Name: 총이용량, dtype: int64

In [162]:
# • 가장바쁜날짜찾기. => 이용일자별 이용자수 합계가 가장 많은 날짜 출력
result = df.groupby('이용일자')['이용자수'].sum().sort_values(ascending = False)
print(result)
print(f"가장 바쁜 날짜 : {result.index[0]}")

이용일자
2024-01-02    420
2024-01-01    400
Name: 이용자수, dtype: int64
가장 바쁜 날짜 : 2024-01-02

In [165]:
# • 이용자수평균이가장높은대여소찾기.
result = df.groupby('대여소')['이용자수'].mean().sort_values(ascending = False)
print(result)
print(f"평균 이용자수 가장 높은 대여소 : {result.index[0]}")

대여소
잠실    190.0
강남    135.0
홍대     85.0
Name: 이용자수, dtype: float64
평균 이용자수 가장 높은 대여소 : 잠실