In [5]:
import pandas as pd

# 공공 데이터 포털에서 다운로드 받은 bike02.csv 파일을 읽어오는 방법
df = pd.read_csv('greenData/bike02.csv', encoding='cp949')
# 상위10개출력한다.
print(df.head(10))

         대여일자    대여건수
0  2025-07-01  132914
1  2025-07-02  151653
2  2025-07-03  151092
3  2025-07-04  151367
4  2025-07-05  118354
5  2025-07-06  106785
6  2025-07-07  146664
7  2025-07-08  115371
8  2025-07-09  136307
9  2025-07-10  139733

In [7]:
# 대여건수가1000 이상인데이터만추출
df[df['대여건수'] >= 1000]

           대여일자    대여건수
0    2025-07-01  132914
1    2025-07-02  151653
2    2025-07-03  151092
3    2025-07-04  151367
4    2025-07-05  118354
..          ...     ...
179  2025-12-27   42381
180  2025-12-28   40774
181  2025-12-29   66652
182  2025-12-30   71026
183  2025-12-31   55570

[184 rows x 2 columns]

In [8]:
# 대여건수기준내림차순정렬
df.sort_values(by='대여건수', ascending = False)

           대여일자    대여건수
87   2025-09-26  176011
93   2025-10-02  175022
84   2025-09-23  173588
91   2025-09-30  170957
92   2025-10-01  169645
..          ...     ...
98   2025-10-07   26673
43   2025-08-13   26358
165  2025-12-13   19152
101  2025-10-10   13940
97   2025-10-06   10493

[184 rows x 2 columns]

In [13]:
# 전체대여건수합계구하기
df.groupby('대여일자')['대여건수'].sum()

대여일자
2025-07-01    132914
2025-07-02    151653
2025-07-03    151092
2025-07-04    151367
2025-07-05    118354
               ...
2025-12-27     42381
2025-12-28     40774
2025-12-29     66652
2025-12-30     71026
2025-12-31     55570
Name: 대여건수, Length: 184, dtype: int64

In [ ]:
# 평균대여건수구하기